version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "1.21.1"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "build"
    commit-message:
      prefix: "build(deps)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "1.21.1"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
